name: Create Flutter Project

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable

      - name: Create Flutter project
        run: |
          flutter create --project-name nasro28 --org com.nasro28 --platforms=android .

      - name: Commit Flutter project
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Create Flutter project"
          git push
